### ISSUE TITLE
Ease people into the experience

### ISSUE THREAD

**Issue by knowtheory** [slifty/aprilbot#6]
For the 2018 Purge, i would like to suggest two possibilities.

First, after some number of frustrated messages, have a resistance bot, or maybe a cultist recruiter bot contact people to introduce them into Thread Resistance or Athreadism.

Second, as an alternative, you could have folks accrue time coin for _not_ participating (the kittens game [uses this as a mechanism](http://bloodrizer.ru/games/kittens/wiki/index.php?page=Time#Temporal_flux_)) so that if they wait for a while, and then come back then they'll be able to participate again.

**Comment by slifty** [comment]
WONTFIX

(jk -- this advice has been integrated into april designs held since)
